import { BuildingNames } from "../../../buildings/buildingNamesType";
import { UpgradeType, UnlockConditionType, UpgradeVariantsType } from "../UpgradeType";

const baseDrawingHandUpgrade = {
    building: "Drawing hand" as BuildingNames,
    buildingId: 0,
    unlockCondition: "Building amount" as UnlockConditionType,
    variant: "Standard building" as UpgradeVariantsType,
};

export const drawingHandUpgrades: UpgradeType[] = [
    {
        ...baseDrawingHandUpgrade,
        name: "Stronger arm",
        icon: "💪",
        description: "A stronger arm makes for drawing emojis faster.",
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 0,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Flexible fingers",
        icon: "🖖",
        description: "Flexible fingers allow for more intricate emojis.",
        categories: ["Multiply building production"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 0,
        tier: 1,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Two hands",
        icon: "👐",
        description: "Twice the hands, double the emojis.",
        categories: ["Multiply building production"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 0,
        tier: 2,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Nail polished hands",
        icon: "💅",
        description: "Having nail polish makes you tap faster, didn't you know that?",
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 3,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Feet",
        icon: "🦶",
        description: "Drawing with your feet doubles production (and it's not hard at all)!",
        categories: ["Multiply building production"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 0,
        tier: 4,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Tongue",
        icon: "👅",
        description: "With years of practice, you too can learn to draw with your tongue!",
        categories: ["Multiply building production"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 0,
        tier: 5,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Nose",
        icon: "👃",
        description: "Stick a crayon up your nose and draw with it!",
        quote: "*Sniff* Why does the screen smell like feet?",
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 6,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Ear",
        icon: "👂",
        description: "Stick a pen in your ears, turn your head 90 degrees and draw with it!",
        categories: ["Multiply building production"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 0,
        tier: 7,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Mouth",
        icon: "👄",
        description: "Stick a pencil in your mouth and draw with it!",
        categories: ["Multiply building production"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 0,
        tier: 8,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Stronger leg",
        icon: "🦵",
        description: "A stronger leg lets you draw emojis much faster with your feet.",
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 9,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Bigger lungs",
        icon: "🫁",
        description: "Bigger lungs allow for drawing emojis faster.",
        categories: ["Multiply building production"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 0,
        tier: 10,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Bigger brain",
        icon: "🧠",
        description: "A bigger brain unleashes a grand wave of creativity doubling your emoji production!",
        categories: ["Multiply building production"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 0,
        tier: 11,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Hair",
        icon: "💇‍♂️",
        description: "Wield a paintbrush with your hair to create emojis. Who needs hands when you've got style?",
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 12,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Eyebrows",
        icon: "🤨",
        description: "Raise your eyebrows to draw emojis. It's a workout for your face and your creativity!",
        categories: ["Multiply building production"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 0,
        tier: 13,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Back",
        icon: "🧘‍♂️",
        description: "Lie on your back and draw emojis with your hands behind you. It's a stretch and a sketch!",
        categories: ["Multiply building production"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 0,
        tier: 14,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Teeth",
        icon: "🦷",
        description: "Grip a pen with your teeth and draw emojis. Warning: May cause jaw fatigue!",
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 15,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Navel",
        icon: "🤰",
        description: "Draw emojis with your belly button. It's a unique skill that's hard to master!",
        categories: ["Multiply building production"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 0,
        tier: 16,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Echo drawing",
        icon: "📢",
        description: "Every emoji you draw echoes, creating twice as many!",
        categories: ["Multiply building production"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 0,
        tier: 17,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Telekinetic drawing",
        icon: "🧙‍♂️",
        description: "Why use your hands when you can draw emojis with your mind?",
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 18,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Quantum fingers",
        icon: "🌀",
        description: "Quantum entanglement in your fingers allows for drawing emojis at the speed of light.",
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 19,
    },
];
