import { getBuildingUpgradePrice } from "../helpers";
import { BuildingNames } from "../../../buildings/buildingNamesType";
import { UpgradeType, UnlockConditionType, UpgradeVariantsType } from "../UpgradeType";

const baseDrawingHandUpgrade = {
    building: "Drawing hand" as BuildingNames,
    buildingId: 0,
    unlockCondition: "Building amount" as UnlockConditionType,
    variant: "Standard building" as UpgradeVariantsType,
};

export const drawingHandUpgrades: UpgradeType[] = [
    {
        ...baseDrawingHandUpgrade,
        name: "Stronger arm",
        icon: "💪",
        description: "A stronger arm makes for drawing emojis faster.",
        price: getBuildingUpgradePrice(0, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 0,
        id: 0,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Flexible fingers",
        icon: "🖖",
        description: "Flexible fingers allow for more intricate emojis.",
        price: getBuildingUpgradePrice(1, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 1,
        id: 1,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Two hands",
        icon: "👐",
        description: "Twice the hands, double the emojis.",
        price: getBuildingUpgradePrice(2, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 2,
        id: 2,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Nail polished hands",
        icon: "💅",
        description: "Having nail polish makes you tap faster, didn't you know that?",
        price: getBuildingUpgradePrice(3, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 3,
        id: 3,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Feet",
        icon: "🦶",
        description: "Drawing with your feet doubles production (and it's not hard at all)!",
        price: getBuildingUpgradePrice(4, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 4,
        id: 4,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Tongue",
        icon: "👅",
        description: "With years of practice, you too can learn to draw with your tongue!",
        price: getBuildingUpgradePrice(5, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 5,
        id: 5,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Nose",
        icon: "👃",
        description: "Stick a crayon up your nose and draw with it!",
        quote: "*Sniff* Why does the screen smell like feet?",
        price: getBuildingUpgradePrice(6, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 6,
        id: 6,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Ear",
        icon: "👂",
        description: "Stick a pen in your ears, turn your head 90 degrees and draw with it!",
        price: getBuildingUpgradePrice(7, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 7,
        id: 7,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Mouth",
        icon: "👄",
        description: "Stick a pencil in your mouth and draw with it!",
        price: getBuildingUpgradePrice(8, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 8,
        id: 8,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Stronger leg",
        icon: "🦵",
        description: "A stronger leg lets you draw emojis much faster with your feet.",
        price: getBuildingUpgradePrice(9, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 9,
        id: 9,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Bigger lungs",
        icon: "🫁",
        description: "Bigger lungs allow for drawing emojis faster.",
        price: getBuildingUpgradePrice(10, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 10,
        id: 110,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Eye",
        icon: "👁️",
        description: "Stick a pencil into your... you know what, nevermind.",
        quote: "I'm gonna make this pencil disappear!",
        price: getBuildingUpgradePrice(11, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 11,
        id: 111,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Faster heart",
        icon: "🫀",
        description: "A faster heart allows for faster drawing.",
        price: getBuildingUpgradePrice(12, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 12,
        id: 112,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Bionic arm",
        icon: "🦾",
        description: "Bionic arms to draw emojis super fast!",
        price: getBuildingUpgradePrice(13, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 13,
        id: 113,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Mechanical leg",
        icon: "🦿",
        description: "Mechanical legs to draw emojis with your feet super fast!",
        price: getBuildingUpgradePrice(14, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 14,
        id: 114,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Cybernetic ear",
        icon: "🦻",
        description: "Cybernetic ears to draw emojis with your ears super fast!",
        quote: "What?! Huh?! I'm sorry I can't hear a thing. Huh?!",
        price: getBuildingUpgradePrice(15, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 15,
        id: 115,
    },
    {
        ...baseDrawingHandUpgrade,
        name: "Bigger brain",
        icon: "🧠",
        description: "A bigger brain unleashes a grand wave of creativity doubling your emoji production!",
        price: getBuildingUpgradePrice(16, 0),
        categories: ["Multiply building production", "Multiply tap"],
        emojisPerSecondMultiplier: 2,
        emojisPerTapMultiplier: 2,
        tier: 16,
        id: 116,
    },
]