import { BuildingNames } from "../../../buildings/buildingNamesType";
import { UpgradeType, UnlockConditionType, UpgradeVariantsType, UpgradeCateogoriesType } from "../UpgradeType";

const baseFarmUpgrade = {
    building: "Farm" as BuildingNames,
    buildingId: 3,
    unlockCondition: "Building amount" as UnlockConditionType,
    categories: ["Multiply building production" as UpgradeCateogoriesType],
    emojisPerSecondMultiplier: 2,
    emojisPerTapMultiplier: 0,
    variant: "Standard building" as UpgradeVariantsType,
};

const farmHelperUpgrade = {
    ...baseFarmUpgrade,
    categories: ["Percentage increase production" as UpgradeCateogoriesType],
    unlockCondition: "Building helper" as UnlockConditionType,
    emojisPerSecondPercentageIncrease: 0.01,
    variant: "Helper" as UpgradeVariantsType,
};

export const farmUpgrades: UpgradeType[] = [
    {
        ...baseFarmUpgrade,
        name: "Farmers",
        icon: "🧑‍🌾",
        description: "What is a farm without a farmer?!",
        tier: 0,
        id: 300,
    },
    {
        ...baseFarmUpgrade,
        name: "Seedling",
        icon: "🌱",
        description: "You have to start somewhere.",
        quote: "Don't stop beleafing!",
        tier: 1,
        id: 301,
    },
    {
        ...baseFarmUpgrade,
        name: "Better tools",
        icon: "🪚",
        description: "Allows for much faster farming!",
        tier: 2,
        id: 302,
    },
    {
        ...baseFarmUpgrade,
        name: "Tractors",
        icon: "🚜",
        description: "Makes emoji-harvesting so much easier.",
        tier: 3,
        id: 303,
    },
    {
        ...baseFarmUpgrade,
        name: "Farmhouses",
        icon: "🏡",
        description: "A cozy home for your farmers to rest and recharge.",
        tier: 4,
        id: 304,
    },
    {
        ...baseFarmUpgrade,
        name: "Emoji cows",
        icon: "🐄",
        description: "Creates more emooooooojis.",
        tier: 5,
        id: 305,
    },
    {
        ...baseFarmUpgrade,
        name: "Irrigation system",
        icon: "💧",
        description: "Keep your emoji crops hydrated for faster growth.",
        quote: "What century is this?!",
        tier: 6,
        id: 306,
    },
    {
        ...baseFarmUpgrade,
        name: "Scarecrows",
        icon: "🎃",
        description: "Keeps those pesky bird emojis away from your farms!",
        tier: 7,
        id: 307,
    },
    {
        ...baseFarmUpgrade,
        name: "Compost bins",
        icon: "🪣",
        description: "Turn waste into fertilizer for healthier emoji crops!",
        tier: 8,
        id: 308,
    },
    {
        ...baseFarmUpgrade,
        name: "Greenhouses",
        icon: "🌿",
        description: "Grow emojis year-round, no matter the weather!",
        tier: 9,
        id: 309,
    },
    {
        ...baseFarmUpgrade,
        name: "Windmills",
        icon: "🌬️",
        description: "Harness the power of the wind to boost your farm's efficiency!",
        quote: "Whoosh!",
        tier: 10,
        id: 310,
    },
    {
        ...baseFarmUpgrade,
        name: "Emoji orchards",
        icon: "🌳",
        description: "Grow emoji trees that bear fruit year-round!",
        tier: 11,
        id: 311,
    },
    {
        ...baseFarmUpgrade,
        name: "Harvest festival",
        icon: "🎪",
        description: "Celebrate your bountiful harvest with a festival that boosts morale!",
        tier: 12,
        id: 312,
    },
    {
        ...baseFarmUpgrade,
        name: "Giant Emoji Slingshot",
        icon: "🪀",
        description: "Launch emoji seeds across your farm for rapid planting!",
        tier: 13,
        id: 313,
    },
    {
        ...baseFarmUpgrade,
        name: "Invisible fencing",
        icon: "🚧",
        description: "Keeps your emoji livestock contained... even if you can't see it.",
        quote: "Hurts when you pee on it.",
        tier: 14,
        id: 314,
    },
    {
        ...baseFarmUpgrade,
        name: "Genetically modified crops",
        icon: "🧬",
        description: "Skinless bananas, strawberries already dipped in chocolate, pre-boiled potatoes and more!",
        tier: 15,
        id: 315,
    },
    {
        ...baseFarmUpgrade,
        name: "The Emoji Farm of the Future",
        icon: "🤖",
        description: "Your farms are now high-tech utopias with robots, holograms, and flying tractors. Welcome to the future!",
        tier: 16,
        id: 316,
    },
    {
        ...baseFarmUpgrade,
        name: "Blood moon",
        icon: "🌕",
        description: "Under the blood moon, your crops grow faster... but they also grow teeth.",
        tier: 17,
        id: 317,
    },
    {
        ...baseFarmUpgrade,
        name: "The final harvest",
        icon: "⚰️",
        description: "A mysterious figure appears, offering a bountiful harvest in exchange for... something. Do you dare accept?",
        tier: 18,
        id: 318,
    },
    {
        ...baseFarmUpgrade,
        name: "Giving up farming",
        icon: "🏢",
        description: "You've grown tired of farming. Maybe the best thing to do is just give up farming and work in an office instead.",
        tier: 19,
        id: 319,
    },


    {
        ...farmHelperUpgrade,
        name: "Potatoes",
        icon: "🥔",
        description: "Spud-tacular! Potatoes are the backbone of any farm.",
        variant: "Helper",
        tier: 0,
        tierPosition: 0,
        id: 30000
    },
    {
        ...farmHelperUpgrade,
        name: "Carrots",
        icon: "🥕",
        description: "Orange you glad we have carrots?",
        variant: "Helper",
        tier: 0,
        tierPosition: 1,
        id: 30001
    },
    {
        ...farmHelperUpgrade,
        name: "Cucumbers",
        icon: "🥒",
        description: "Cool as a cucumber! These refreshing veggies are perfect for salads and pickling.",
        quote: "I'm pickle Rick!",
        variant: "Helper",
        tier: 0,
        tierPosition: 2,
        id: 30002
    },
    {
        ...farmHelperUpgrade,
        name: "Bell peppers",
        icon: "🫑",
        description: "Sweet or spicy, bell peppers add a pop of color and flavor to your farm.",
        quote: "No point ringing this...",
        variant: "Helper",
        tier: 0,
        tierPosition: 3,
        id: 30003
    },
    {
        ...farmHelperUpgrade,
        name: "Tomatoes",
        icon: "🍅",
        description: "Juicy and versatile, tomatoes are a farm favorite.",
        variant: "Helper",
        tier: 0,
        tierPosition: 4,
        id: 30004
    },
    {
        ...farmHelperUpgrade,
        name: "Lettuce",
        icon: "🥬",
        description: "Leaf it to lettuce to keep your farm fresh and green.",
        variant: "Helper",
        tier: 0,
        tierPosition: 5,
        id: 30005
    },
    {
        ...farmHelperUpgrade,
        name: "Broccoli",
        icon: "🥦",
        description: "Tiny trees with big benefits!",
        quote: "Don't tell Broccoli Rob.",
        variant: "Helper",
        tier: 0,
        tierPosition: 6,
        id: 30006
    },
    {
        ...farmHelperUpgrade,
        name: "Onions",
        icon: "🧅",
        description: "Layered with flavor and tears, onions are a kitchen staple and a farm essential.",
        quote: "Ogres are like onions. Onions have layers. Ogres have layers.",
        variant: "Helper",
        tier: 0,
        tierPosition: 7,
        id: 30007
    },
    {
        ...farmHelperUpgrade,
        name: "Garlic",
        icon: "🧄",
        description: "Garlic adds flavor to your dishes and protection to your farm.",
        quote: "Works great if you have a vampire problem!",
        variant: "Helper",
        tier: 0,
        tierPosition: 8,
        id: 30008
    },
    {
        ...farmHelperUpgrade,
        name: "Corn",
        icon: "🌽",
        description: "Corn is a versatile crop that's perfect for roasting and popping.",
        quote: "A-maize-ing!",
        variant: "Helper",
        tier: 0,
        tierPosition: 9,
        id: 30009
    },
    // Tier 2
    {
        ...farmHelperUpgrade,
        name: "Beans",
        icon: "🫘",
        description: "High in protein and perfect for expanding your farm.",
        quote: "Beans!",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.02,
        tier: 1,
        tierPosition: 0,
        id: 30010
    },
    {
        ...farmHelperUpgrade,
        name: "Peanuts",
        icon: "🥜",
        description: "Nutty and delicious, peanuts are great for snacking and boosting your farm's productivity.",
        quote: "They say Jimmy liked these.",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.02,
        tier: 1,
        tierPosition: 1,
        id: 30011
    },
    {
        ...farmHelperUpgrade,
        name: "Pumpkins",
        icon: "🎃",
        description: "Giant, orange, and perfect for pies or scaring crows. Pumpkins are a fall favorite!",
        quote: "Pumpkin spice and everything nice!",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.02,
        tier: 1,
        tierPosition: 2,
        id: 30012
    },
    {
        ...farmHelperUpgrade,
        name: "Strawberries",
        icon: "🍓",
        description: "Sweet, juicy, and perfect for desserts. Strawberries are a berry good addition to your farm!",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.02,
        tier: 1,
        tierPosition: 3,
        id: 30013
    },
    {
        ...farmHelperUpgrade,
        name: "Blueberries",
        icon: "🫐",
        description: "Tiny but mighty..",
        quote: "I'm blue da ba dee da ba di",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.02,
        tier: 1,
        tierPosition: 4,
        id: 30014
    },
    {
        ...farmHelperUpgrade,
        name: "Eggplants",
        icon: "🍆",
        description: "Purple and versatile, eggplants are perfect for grilling, roasting, and emoji farming.",
        quote: "My boyfriend's favorite emoji is the eggplant, he keeps sending it to me!",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.02,
        tier: 1,
        tierPosition: 5,
        id: 30015
    },
    {
        ...farmHelperUpgrade,
        name: "Zucchinis",
        icon: "🥒",
        description: "Green and abundant, zucchinis are a summer squash that keeps on giving.",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.02,
        tier: 1,
        tierPosition: 6,
        id: 30016
    },
    {
        ...farmHelperUpgrade,
        name: "Avocados",
        icon: "🥑",
        description: "Creamy and delicious, avocados are the toast of the town and a farm favorite.",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.02,
        tier: 1,
        tierPosition: 7,
        id: 30017
    },
    {
        ...farmHelperUpgrade,
        name: "Sweet Potatoes",
        icon: "🍠",
        description: "Potato's sweet cousin.",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.02,
        tier: 1,
        tierPosition: 8,
        id: 30018
    },
    {
        ...farmHelperUpgrade,
        name: "Peas",
        icon: "🫛",
        description: "Peas!",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.02,
        tier: 1,
        tierPosition: 9,
        id: 30019
    },
    // Tier 3
    {
        ...farmHelperUpgrade,
        name: "Radishes",
        icon: "🌶️",
        description: "Spicy and crunchy, radishes add a kick to your farm and your dishes.",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.03,
        tier: 2,
        tierPosition: 0,
        id: 30020
    },
    {
        ...farmHelperUpgrade,
        name: "Mushrooms",
        icon: "🍄",
        description: "Fungi fun! Mushrooms are as mysterious as they are delicious.",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.03,
        tier: 2,
        tierPosition: 1,
        id: 30021
    },
    {
        ...farmHelperUpgrade,
        name: "Pineapples",
        icon: "🍍",
        description: "Tropical and tangy.",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.03,
        tier: 2,
        tierPosition: 2,
        id: 30022
    },
    {
        ...farmHelperUpgrade,
        name: "Watermelons",
        icon: "🍉",
        description: "Juicy and refreshing, watermelons are the ultimate summer crop.",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.03,
        tier: 2,
        tierPosition: 3,
        id: 30023
    },
    {
        ...farmHelperUpgrade,
        name: "Kiwis",
        icon: "🥝",
        description: "Fuzzy on the outside, sweet on the inside. Kiwis are a farm favorite!",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.03,
        tier: 2,
        tierPosition: 4,
        id: 30024
    },
    {
        ...farmHelperUpgrade,
        name: "Grapes",
        icon: "🍇",
        description: "Perfect for snacking, juicing, or turning into wine.",
        quote: "In grapes, there is truth.",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.03,
        tier: 2,
        tierPosition: 5,
        id: 30025
    },
    {
        ...farmHelperUpgrade,
        name: "Cherries",
        icon: "🍒",
        description: "Sweet and tart, cherries are a delightful treat and a farm favorite.",
        variant: "Helper",
        emojisPerSecondPercentageIncrease: 0.03,
        tier: 2,
        tierPosition: 6,
        id: 30026
    },
];
