import { BuildingNames } from "../../../buildings/buildingNamesType";
import { UpgradeType, UnlockConditionType, UpgradeVariantsType, UpgradeCateogoriesType } from "../UpgradeType";

const baseGraphicDesignStudioUpgrade = {
    building: "Graphic design studio" as BuildingNames,
    buildingId: 1,
    unlockCondition: "Building amount" as UnlockConditionType,
    categories: ["Multiply building production" as UpgradeCateogoriesType],
    emojisPerSecondMultiplier: 2,
    emojisPerTapMultiplier: 0,
    variant: "Standard building" as UpgradeVariantsType,
};

export const graphicDesignStudioUpgrades: UpgradeType[] = [
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Improved pencils",
        icon: "✏️",
        description: "Better pencils for more detailed emojis.",
        tier: 0,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Specialized crayons",
        icon: "🖍️",
        description: "These special crayons allow artists to access their inner child.",
        tier: 1,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Improved brushes",
        icon: "🖌️",
        description: "Improved brushes allow for more artistic emojis.",
        tier: 2,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Fountain pens",
        icon: "🖋️",
        description: "Allows for more distinguished emojis.",
        tier: 3,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Rulers",
        icon: "📏",
        description: "How else would you draw a straight line?",
        tier: 4,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Color Blindness Simulator",
        icon: "👓",
        description: "Ensure your emojis are accessible to everyone!",
        quote: "Is it 'Wuh-cag'? 'Double-you-cag'? 'Wee-cag'?",
        tier: 5,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Comic book effects",
        icon: "💥",
        description: "Add 'POW!' and 'BAM!' effects to your emojis for extra flair!",
        tier: 6,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Stencil kit",
        icon: "🖼️",
        description: "Perfectly shaped emojis every time with these stencils!",
        tier: 7,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Custom keyboard shortcuts",
        icon: "⌨️",
        description: "Speed up your workflow with personalized shortcuts for emoji design!",
        quote: "Try alt + F4.",
        tier: 8,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Asset library subscription",
        icon: "📚",
        description: "Access a vast library of pre-made shapes, icons, and textures!",
        tier: 9,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Undo button",
        icon: "🔙",
        description: "Pressing undo doesn't just revert your work - it alters reality itself. Use sparingly.",
        quote: "To err is human",
        tier: 10,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Emoji coloring book",
        icon: "📘",
        description: "Only the most refined artists use coloring books.",
        tier: 11,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Real-time collaboration",
        icon: "👥",
        description: "Invite other designers to work on your emoji projects simultaneously!",
        tier: 12,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Emoji mood board",
        icon: "📌",
        description: "Organize your emoji ideas visually for maximum creativity!",
        quote: "Why do you look so board?",
        tier: 13,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Pixel art software",
        icon: "🖥️",
        description: "Create retro-style pixelated emojis that scream '90s nostalgia!",
        quote: "Every pixel matters.",
        tier: 14,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Comic Sans font",
        icon: "📝",
        description: "Love it or hate it, it makes your emojis look... unique!",
        tier: 15,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "AI art generator",
        icon: "🤖",
        description: "Let AI do the heavy lifting and generate low quality and boring emojis at lightning speed!",
        quote: "Beep boop!",
        tier: 16,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Origami Paper",
        icon: "🦢",
        description: "Fold your paper emojis into all sorts of shapes!",
        quote: "Quack!",
        tier: 17,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Emoji tattoo gun",
        icon: "💉",
        description: "Permanent emojis for the truly committed artist!",
        quote: "Ouch!",
        tier: 18,
    },
    {
        ...baseGraphicDesignStudioUpgrade,
        name: "Blood",
        icon: "🩸",
        description: "Painting with blood makes for extra cool emojis!",
        tier: 19,
    },
];