import { BuildingNames } from "../../../buildings/buildingNamesType";
import { UpgradeType, UnlockConditionType, UpgradeVariantsType, UpgradeCateogoriesType } from "../UpgradeType";

const baseRestaurantUpgrade = {
    building: "Restaurant" as BuildingNames,
    buildingId: 4,
    unlockCondition: "Building amount" as UnlockConditionType,
    categories: ["Multiply building production" as UpgradeCateogoriesType],
    emojisPerSecondMultiplier: 2,
    emojisPerTapMultiplier: 0,
    variant: "Standard building" as UpgradeVariantsType,
};

export const restaurantUpgrades: UpgradeType[] = [
    {
        ...baseRestaurantUpgrade,
        name: "Sharp Knives",
        icon: "🔪",
        description: "Sharper knives make chopping emojis easier.",
        tier: 0,
        id: 400,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Non-Stick Pans",
        icon: "🍳",
        description: "Non-stick pans make cooking emoji meals faster.",
        tier: 1,
        id: 401,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Better Ovens",
        icon: "🥖",
        description: "Ovens with better heat control cook emojis quicker.",
        tier: 2,
        id: 402,
    },
    {
        ...baseRestaurantUpgrade,
        name: "High-Quality Ingredients",
        icon: "🥗",
        description: "Higher quality ingredients mean tastier emojis.",
        tier: 3,
        id: 403,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Chef's Hat",
        icon: "👨‍🍳",
        description: "Wearing a chef's hat boosts emoji cooking speed.",
        tier: 4,
        id: 404,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Emoji Blenders",
        icon: "🥤",
        description: "Blend emojis into delicious smoothies and soups in seconds!",
        tier: 5,
        id: 405,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Airfryers",
        icon: "🍟",
        description: "Fry emojis to perfection in record time. Crispy and golden every time!",
        tier: 6,
        id: 406,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Sushi Bars",
        icon: "🍣",
        description: "Roll up emoji sushi with precision and style. Raw talent required!",
        tier: 7,
        id: 407,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Salad Bars",
        icon: "🥗",
        description: "Toss together fresh emoji salads with a variety of toppings. Healthy and delicious!",
        tier: 8,
        id: 408,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Pizza Ovens",
        icon: "🍕",
        description: "Bake emoji pizzas with a wood-fired flavor that’s out of this world!",
        tier: 9,
        id: 409,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Emoji Coffee Machines",
        icon: "☕",
        description: "Brew the perfect cup of emoji coffee to keep your chefs energized!",
        tier: 10,
        id: 410,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Emoji Ice Cream Machines",
        icon: "🍦",
        description: "Churn out frozen emoji treats that are as cool as they are delicious!",
        tier: 11,
        id: 411,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Taco Stations",
        icon: "🌮",
        description: "Assemble emoji tacos with all the toppings. It's a fiesta in every bite!",
        quote: "¡Ay, caramba!",
        tier: 12,
        id: 412,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Waffle Irons",
        icon: "🧇",
        description: "Cook emoji waffles with crispy edges and fluffy insides. Perfect for brunch!",
        tier: 13,
        id: 413,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Emoji Chocolate Fountains",
        icon: "🍫",
        description: "Drizzle melted emoji chocolate over everything. Sweet and indulgent!",
        tier: 14,
        id: 414,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Emoji Cannibal Kitchen",
        icon: "😱",
        description: "Cook emojis using other emojis as ingredients.",
        tier: 15,
        id: 415,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Emoji Black Hole Fryer",
        icon: "🕳️",
        description: "Fry emojis in a black hole, harnessing its immense energy. They come back crispy!",
        tier: 16,
        id: 416,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Emoji Food Fight Arena",
        icon: "🤼",
        description: "Turn your kitchen into a food fight arena. It's messy, chaotic, and strangely profitable.",
        tier: 17,
        id: 417,
    },
    {
        ...baseRestaurantUpgrade,
        name: "Living Dough",
        icon: "🍞",
        description: "This dough moves on its own, shaping itself into perfect emoji bread. Sometimes it tries to escape.",
        tier: 18,
        id: 418,
    },
    {
        ...baseRestaurantUpgrade,
        name: "The Infinite Buffet",
        icon: "🌀",
        description: "A buffet that never ends... but the food might start eating you instead.",
        tier: 19,
        id: 419,
    },
];
