import { Effect } from "./effectType";

const effectEmojis = [
    "🚀",
    "💎",
    "🌟",
    "⚡",
    "🍀",
    "💰",
    "📈",
    "🏆"
];

export const effectData: Effect[] = [
    {
        title: "x2 tapping power",
        description: "Emojis per tap doubled!",
        eptMult: 2,
        eptAdd: 0,
        epsMult: 0,
        timeLeft: 20,
        timeLeftOnScreen: 25,
        displayMeter: true,
        emoji: "🚀",
        xPos: 100,
        yPos: 100,
        id: 0,
        type: "tap",
        quality: "good",
    },
    {
        title: "x3 tapping power",
        description: "Emojis per tap tripled!",
        eptMult: 3,
        eptAdd: 0,
        epsMult: 0,
        timeLeft: 15,
        timeLeftOnScreen: 25,
        displayMeter: true,
        emoji: "💎",
        xPos: 100,
        yPos: 100,
        id: 1,
        type: "tap",
        quality: "good",
    },
    // Production multiplier effects
    {
        title: "x2 emoji production",
        description: "Emoji production doubled!",
        eptMult: 0,
        eptAdd: 0,
        epsMult: 2,
        timeLeft: 30,
        timeLeftOnScreen: 25,
        displayMeter: true,
        emoji: "🍀",
        xPos: 100,
        yPos: 100,
        id: 100,
        type: "production",
        quality: "good",
    },
    {
        title: "x77 emoji production",
        description: "Emoji production doubled!",
        eptMult: 0,
        eptAdd: 0,
        epsMult: 77,
        timeLeft: 4,
        timeLeftOnScreen: 10,
        displayMeter: true,
        emoji: "😈",
        xPos: 100,
        yPos: 100,
        id: 101,
        type: "production",
        quality: "good",
    },
    {
        title: "Half emoji production",
        description: "Emoji production halved!",
        eptMult: 0,
        eptAdd: 0,
        epsMult: 0.5,
        timeLeft: 15,
        timeLeftOnScreen: 15,
        displayMeter: true,
        emoji: "💣",
        xPos: 100,
        yPos: 100,
        id: 110,
        type: "production",
        quality: "bad",
    },

    {
        title: "Emoji gift",
        description: "1 hour's worth of emojis!",
        eptMult: 0,
        eptAdd: 0,
        epsMult: 0,
        timeLeft: 0,
        timeLeftOnScreen: 25,
        displayMeter: false,
        emoji: "🎁",
        xPos: 100,
        yPos: 100,
        id: 200,
        type: "give",
        quality: "good",
    },

]